// @vitest-environment jsdom

/**
 * Component tests for `<ReportBlock />`.
 *
 * Reports are rendered with paragraph formatting: blank-line-delimited
 * paragraphs in the stored text are split into discrete `<p>` elements so
 * prose generated by the report summarizer flows naturally (Req 11.1).
 *
 * Validates: Requirements 11.1
 *
 * Notes on test mechanics:
 *  - `cleanup()` runs after each test to unmount React trees so the next
 *    test starts from a fresh DOM.
 *  - We assert the *paragraph count and content* by querying the inner
 *    text container's `<p>` children. The article also contains a
 *    distance footer rendered as a `<p>`, so we narrow the query to the
 *    first `<div>` (the text container) before counting paragraphs.
 */

import { afterEach, describe, expect, it } from "vitest";
import { cleanup, render, screen } from "@testing-library/react";

import type { RecallEntry } from "@uberwal/shared";

import { ReportBlock } from "./ReportBlock";

describe("<ReportBlock />", () => {
  afterEach(() => {
    cleanup();
  });

  it("renders multiple <p> elements for blank-line-delimited paragraphs (Req 11.1)", () => {
    const reportText = [
      "First paragraph covering skill portfolio highlights.",
      "Second paragraph summarizing productivity patterns.",
      "Third paragraph with closing observations.",
    ].join("\n\n");

    const entry: RecallEntry = {
      blob_id: "blob-1",
      text: reportText,
      distance: 0.18,
    };

    render(<ReportBlock entry={entry} />);

    const article = screen.getByRole("article");
    // The first <div> inside the article is the paragraph container; the
    // distance score is rendered separately afterwards as its own <p>.
    const paragraphContainer = article.querySelector("div");
    expect(paragraphContainer).not.toBeNull();

    const paragraphs = paragraphContainer!.querySelectorAll("p");
    expect(paragraphs.length).toBe(3);

    expect(paragraphs[0]?.textContent).toBe(
      "First paragraph covering skill portfolio highlights.",
    );
    expect(paragraphs[1]?.textContent).toBe(
      "Second paragraph summarizing productivity patterns.",
    );
    expect(paragraphs[2]?.textContent).toBe(
      "Third paragraph with closing observations.",
    );
  });

  it("renders a single <p> when the text contains no blank lines", () => {
    const entry: RecallEntry = {
      blob_id: "blob-2",
      // A single newline does not introduce a paragraph break — only a
      // blank line (two consecutive newlines) does.
      text: "Single paragraph report.\nWith a soft line break inside.",
      distance: 0.22,
    };

    render(<ReportBlock entry={entry} />);

    const article = screen.getByRole("article");
    const paragraphContainer = article.querySelector("div");
    expect(paragraphContainer).not.toBeNull();

    const paragraphs = paragraphContainer!.querySelectorAll("p");
    expect(paragraphs.length).toBe(1);
    expect(paragraphs[0]?.textContent).toBe(
      "Single paragraph report.\nWith a soft line break inside.",
    );
  });

  it("tolerates extra blank lines without rendering empty paragraphs", () => {
    const entry: RecallEntry = {
      blob_id: "blob-3",
      // Three consecutive newlines (one blank line plus an extra) and
      // surrounding whitespace should not produce ghost paragraphs.
      text: "\n\nFirst.\n\n\nSecond.\n\n",
      distance: 0.35,
    };

    render(<ReportBlock entry={entry} />);

    const article = screen.getByRole("article");
    const paragraphContainer = article.querySelector("div");
    const paragraphs = paragraphContainer!.querySelectorAll("p");

    expect(paragraphs.length).toBe(2);
    expect(paragraphs[0]?.textContent).toBe("First.");
    expect(paragraphs[1]?.textContent).toBe("Second.");
  });
});
